package:
  name: lua-cutorch
  version: 7

source:
  git_url: https://github.com/torch/cutorch.git
  git_rev: 50bfa8d

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch

test:
  commands:
    - lua -e "require 'cutorch'"

about:
  home: https://github.com/torch/cutorch
  license: BSD
  summary: Torch CUDA Implementation