package:
  name: lua-cutorch7
  version: 1.0

source:
  git_url: git@github.com:torch/cutorch.git
  git_rev: 0903d5763025d163c575b11d5a51ce3d760c3ad1

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch

test:
  commands:
    - lua -e "require 'cutorch'"

about:
  home: https://github.com/torch/cutorch
  license: BSD