package:
  name: lua-xlua
  version: 1.1

source:
  git_url: git@github.com:torch/xlua.git
  git_rev: 3c1d3c9

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-sys
  run:
    - luarocks
    - lua
    - lua-torch
    - lua-sys

test:
  commands:
    - lua -e "require 'xlua'"

about:
  home: https://github.com/torch/xlua
  license: BSD
  summary: Extra Lua functions