package:
  name: lua
  version: 2.0.4 # for some reason, versions must be uppercase if alphabetical and in front of numbers,
                    # but you can have whatever text you want after numbers

source:
  fn: LuaJIT-2.0.4.tar.gz
  url: http://luajit.org/download/LuaJIT-2.0.4.tar.gz
  md5: dd9c38307f2223a504cbfb96e477eca0

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - readline
  run:
    - readline

test:
  commands:
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://luajit.org/
  summary: A Just-In-Time Compiler for Lua
  license: MIT