package:
  name: lua
  version: 2.0.4jit # for some reason, versions must be uppercase if alphabetical

source:
  fn: LuaJIT-2.0.4.tar.gz
  url: http://luajit.org/download/LuaJIT-2.0.4.tar.gz
  md5: dd9c38307f2223a504cbfb96e477eca0

build:
  number: 1
  detect_binary_files_with_prefix: true

test:
  commands:
    - luajit -v

about:
  home: http://luajit.org/
  summary: A Just-In-Time Compiler for Lua
  license: MIT