package:
  name: lua-torchx
  version: 0.1.1

source:
  git_url: https://github.com/nicholas-leonard/torchx.git
  git_rev: 06cdbd3

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-paths
    - lua-sys
    - lua-luaffi [not luajit]
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-paths
    - lua-sys
    - lua-luaffi [not luajit]

test:
  commands:
    - lua -e "require 'torchx'"

about:
  home: https://github.com/nicholas-leonard/torchx
  summary: Torch extensions