package:
  name: sox
  version: 14.4.2

source:
  fn: sox-14.4.2.tar.gz
  url: http://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.gz
  md5: d04fba2d9245e661f245de0577f48a33

build:
  number: 0
  detect_binary_files_with_prefix: true

about:
  home: http://sox.sourceforge.net/
  license: LGPL