package:
  name: lua-image
  version: 1.1.0

source:
  git_url: https://github.com/torch/image.git
  git_rev:  24b1e7e

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-xlua
    - lua-sys
    - lua-dok
    - jpeg
    - libpng
    - zlib
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-xlua
    - lua-sys
    - lua-dok
    - jpeg
    - libpng
    - zlib

test:
  commands:
    - lua -e "require 'image'"

about:
  home: https://github.com/torch/image
  license: BSD
  summary: An image library for Torch