package:
  name: lua-base64
  version: 0.2

source:
  fn: lbase64.tar.gz
  url: http://webserver2.tecgraf.puc-rio.br/~lhf/ftp/lua/5.1/lbase64.tar.gz
  md5: 4834045fe79facef524990e968783dab

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit
    - luarocks

test:
  commands:
    - luajit -e "require 'base64'"

about:
  home: http://www.tecgraf.puc-rio.br/~lhf/ftp/lua/
  license: Public domain