cmake -E make_directory build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
		 -DLUA_INCDIR=$INCLUDE_PATH/luajit-2.0 \
		 -DLUA_LIBDIR=$LIBRARY_PATH \
		 -DLUADIR=${PREFIX} \
		 -DLIBDIR=${LIBRARY_PATH} \
		 -DCMAKE_INSTALL_PREFIX=${PREFIX}
make
make install PREFIX=$PREFIX BINDIR=$PREFIX/bin LIBDIR=$LIBRARY_PATH LUADIR=$PREFIX CONFDIR=$PREFIX