package:
  name: lua-paths
  version: 1.0

source:
  fn: 328d5c17c44b4c7cb0623103c926dbae215745e4.tar.gz
  url: https://github.com/torch/paths/archive/328d5c17c44b4c7cb0623103c926dbae215745e4.tar.gz
  md5: 2cb2f70b76823c0f7bd7827cc846a891

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - cmake
    - luarocks
  run:
    - luarocks
    - luajit

test:
  commands:
    - luajit -e "require 'paths'"

about:
  home: https://github.com/torch/paths
  license: BSD