package:
  name: lua-sys
  version: 1.1

source:
  git_url: git@github.com:torch/sys.git
  git_tag: 1.1-0

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
  run:
    - luajit
    - lua-torch7

test:
  commands:
    - luajit -e "require 'sys'"

about:
  home: https://github.com/torch/sys
  license: BSD