# From: https://github.com/numba/llvmlite
package:
  name: llvm-clang
  version: "3.6.2"

source:
  fn: clang+llvm-3.6.2-x86_64-apple-darwin.tar.xz [osx]
  url: http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-apple-darwin.tar.xz [osx]
  fn: clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz [linux]
  url: http://llvm.org/releases/3.6.2/clang+llvm-3.6.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz [linux]
  # fn: llvm-3.6.2.src.tar.xz
  # url: http://llvm.org/releases/3.6.2/llvm-3.6.2.src.tar.xz
  # sha1: 7a00257eb2bc9431e4c77c3a36b033072c54bc7e
  # patches:
  #   # From http://reviews.llvm.org/D6052
  #   - llvm-elf-relocation.patch

build:
  number: 1

# requirements:
#   build:
#     - system           [linux and not armv7l]
#   run:
#     - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [not win]
    - llc -version         [not win]
    - clang --version
    - clang++ --version

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.6.0/LICENSE.TXT)
  summary: LLVM and Clang
