package:
  name: lua-cwrap
  version: 0.1

source:
  git_url: https://github.com/torch/cwrap.git
  git_rev: dbd0a623dc4dfb4b8169d5aecc6dd9aec2f22792 # be920f1f3829ec8c729950f064108442e1547132

build:
  number: 2

requirements:
  build:
    - lua
    - luarocks
  run:
    - lua
    - luarocks

test:
  commands:
    - lua -e "require 'cwrap'"
    - lua -e "require 'cwrap.cinterface'"
    - lua -e "require 'cwrap.types'"

about:
  home: https://github.com/torch/cwrap
  license: BSD
  summary: Advanced automatic wrapper for C functions