package:
  name: glog
  version: 0.3.4

source:
  git_url: https://github.com/google/glog.git
  git_tag: v0.3.4

build:
  number: 1
  detect_binary_files_with_prefix: true

about:
  home: https://github.com/google/glog
  license: Apache