package:
  name: glog
  version: 0.3.4

source:
  url: https://github.com/google/glog/archive/v0.3.4.tar.gz
  fn: v0.3.4.tar.gz

build:
  number: 2
  binary_relocation: true
  detect_binary_files_with_prefix: true

about:
  home: https://github.com/google/glog
  license: Apache