package:
  name: lua
  version: 5.3.2

source:
  fn: lua-5.3.2.tar.gz
  url: http://www.lua.org/ftp/lua-5.3.2.tar.gz
  md5: 33278c2ab5ee3c1a875be8d55c1ca2a1

build:
  number: 1
  # detect_binary_files_with_prefix: true

requirements:
  build:
    - readline
  run:
    - readline

test:
  commands:
    - lua -v

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT