package:
  name: lua-trepl
  version: 1.0

source:
  git_url: git@github.com:torch/trepl.git
  git_rev: 468aa304ba9e3dae9a836b553614f14754b563f8

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight
  run:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight

test:
  commands:
    - luajit -e "require 'trepl'"

about:
  home: https://github.com/torch/trepl
  license: Unlicensed