# From: https://github.com/numba/llvmlite
package:
  name: llvm-clang
  version: "3.5.2"

source:
  fn: llvm-3.5.2.src.tar.xz
  url: http://llvm.org/releases/3.5.2/llvm-3.5.2.src.tar.xz
  sha1: 85faf7cbd518dabeafc4d3f7e909338fc1dab3c4
  # fn: clang+llvm-3.5.2-x86_64-apple-darwin.tar.xz [osx]
  # url: http://llvm.org/releases/3.5.2/clang+llvm-3.5.2-x86_64-apple-darwin.tar.xz [osx]
  # fn: clang+llvm-3.5.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz [linux]
  # url: http://llvm.org/releases/3.5.2/clang+llvm-3.5.2-x86_64-linux-gnu-ubuntu-14.04.tar.xz [linux]
  # patches:
    # From http://reviews.llvm.org/D6052
    # - llvm-elf-relocation.patch

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - system           [linux and not armv7l]
  run:
    - python
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [not win]
    - llc -version         [not win]
    - clang --version
    - clang++ --version

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.5.0/LICENSE.TXT)
  summary: LLVM and Clang
