package:
  name: lua-crypto
  version: 0.3.2

source:
  git_url: https://github.com/starius/luacrypto.git
  git_rev: ab1caf241876466e928a5ccb7a99cfef81387730

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - openssl
  run:
    - lua
    - luarocks
    - openssl

test:
  commands:
    - lua -e "require 'crypto'"

about:
  home: http://mkottman.github.com/luacrypto/
  license: MIT