package:
  name: lua-science
  version: 1.0

build:
  number: 1

requirements:
  build:
    - lua
    - luarocks
    - lua-cjson
    - lua-torch
    - lua-nn
    - lua-nngraph
    - lua-distributions
    - lua-randomkit
    - lua-cephes
    - lua-signal
    - lua-audio
    - lua-pprint
    - lua-optim
    - lua-hdf5 [luajit]
    - lua-totem
    - lua-image
    - lua-graph
    - lua-trepl
    - lua-xlua
    - lua-sys
    - lua-paths
    - lua-class
    - lua-argcheck
    - lua-penlight
    - lua-itorch # this pulls in a ton of Python, maybe we don't want that?

  run:
    - lua
    - luarocks
    - lua-cjson
    - lua-torch
    - lua-nn
    - lua-nngraph
    - lua-distributions
    - lua-randomkit
    - lua-cephes
    - lua-signal
    - lua-audio
    - lua-pprint
    - lua-optim
    - lua-hdf5 [luajit]
    - lua-totem
    - lua-image
    - lua-graph
    - lua-trepl
    - lua-xlua
    - lua-sys
    - lua-paths
    - lua-class
    - lua-argcheck
    - lua-penlight
    - lua-itorch # this pulls in a ton of Python, maybe we don't want that?

about:
  home: http://www.github.com.org/alexbw
  summary: An easy-to-install Lua distribution for science and machine learning
  license: MIT