package:
  name: lua-pprint
  version: 0.1

source:
  git_url: git@github.com:deepmind/lua-pprint.git
  git_rev: 4239fce

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
  run:
    - lua
    - luarocks
    - lua-torch

test:
  commands:
    - lua -e "require 'pprint'"

about:
  home: https://github.com/deepmind/lua-pprint
  license: BSD
  summary: A pretty print library for Torch and lua.