package:
  name: lua-cjson
  version: "2.1.0"

source:
  fn: lua-cjson-2.1.0.zip
  url: http://www.kyne.com.au/~mark/software/download/lua-cjson-2.1.0.zip
  # git_url: http://www.kyne.com.au/~mark/software/download/lua-cjson-2.1.0.zip
  # git_tag:  # can also be a branch, but that is highly discouraged
  # git_rev:  # prefer tags over commits, commits over branches
  # md5:
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # Useful to leave this on by default, will allow relocating
  # packages that have hard-coded paths in them
  detect_binary_files_with_prefix: true
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - luarocks
    - lua

  run:
    - luarocks
    - lua

test:
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - lua -e "require 'cjson'"

  # You can also put a file called run_test.lua in the recipe that will be run
  # at test time.

about:
  home: http://www.kyne.com.au/~mark/software/lua-cjson.php
  license: MIT
  summary: A fast JSON encoding/parsing module

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
