package:
  name: itorch
  version: 1.0

source:
  git_url: git@github.com:facebook/iTorch.git
  git_rev: f111f6d015ec518172b5284718384ead1ae49174

build:
  number: 1
  detect_binary_files_with_prefix: true


requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-base64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - ipython >=3.0
  run:
    - luajit
    - lua-torch7
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-base64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - ipython >=3.0

test:
  commands:
    - itorch --help

about:
  home: https://github.com/facebook/itorch
  license: BSD