package:
  name: lua-torch-distributions
  version: 0.0

source:
  git_url: git@github.com:deepmind/torch-distributions.git
  git_rev: 2a915e274734a52ae406436b3dbc540c66b631c5

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-torch-randomkit
    - lua-penlight
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-torch-randomkit
    - lua-penlight

test:
  commands:
    - lua -e "require 'torch'; require 'distributions'"

about:
  home: https://github.com/deepmind/torch-distributions
  license: BSD