package:
  name: lua-distributions
  version: 0.1

source:
  git_url: https://github.com/deepmind/torch-distributions.git
  git_rev: fb6dd52

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-randomkit
    - lua-penlight # lua 5.1 compatibility
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-randomkit
    - lua-penlight # lua 5.1 compatibility

test:
  commands:
    - lua -e "require 'pl'; require 'torch'; require 'distributions'"

about:
  home: https://github.com/deepmind/torch-distributions
  license: BSD
  summary: Probability distributions