package:
  name: lua-torch-totem
  version: 0.0

source:
  git_url: git@github.com:deepmind/torch-totem.git
  git_rev: 369f185cdaf22f0738ce31d794eb445c5339b271

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight
    - lua-sys
    - lua-nn
  run:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight
    - lua-sys
    - lua-nn

test:
  commands:
    - luajit -e "require 'totem'"

about:
  home: https://github.com/deepmind/torch-totem
  license: BSD