package:
  name: lua-cunn
  version: 0.1.2

source:
  git_url: https://github.com/torch/cunn.git
  git_rev: 9634a07

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-cutorch
    - lua-nn
  run:
    - lua
    - lua-torch
    - lua-cutorch
    - lua-nn

test:
  commands:
    - lua -e "require 'cunn'"

about:
  home: https://github.com/torch/cunn
  license: BSD
  summary: Torch CUDA Neural Network Implementation
