package:
  name: lua-cunn
  version: 0.1

source:
  git_url: git@github.com:torch/cunn.git
  git_rev: 71ca338

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-cutorch
    - lua-nn
    - cmake
  run:
    - lua
    - lua-cutorch
    - lua-nn
    - cmake

test:
  commands:
    - lua -e "require 'cunn'"

about:
  home: https://github.com/torch/cunn
  license: BSD
  summary: Torch CUDA Neural Network Implementation