package:
  name: luarocks
  version: 2.2.1

source:
  # fn: luarocks-2.2.2.tar.gz
  # url: http://luarocks.org/releases/luarocks-2.2.2.tar.gz
  # md5: 5a830953d27715cc955119609f8096e6
  git_url: https://github.com/torch/luajit-rocks.git
  git_rev: 0de2b34
build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
  run:
    - lua

test:
  commands:
    - luarocks --lr-path

about:
  home: http://www.luarocks.org/
  license: MIT