package:
  name: luarocks
  version: 2.2.1

source:
  fn: luarocks-2.2.1.tar.gz
  url: http://luarocks.org/releases/luarocks-2.2.1.tar.gz
  md5: 718a0e8c257aace3ec16ebc2cfe9c696

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
  run:
    - luajit

test:
  commands:
    - luarocks --lr-path

about:
  home: http://www.luarocks.org/
  license: MIT