package:
  name: lua-luafilesystem
  version: 1.6.3

source:
  git_url: git@github.com:keplerproject/luafilesystem
  git_tag: v_1_6_3

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit
    - luarocks

test:
  commands:
    - luajit -e "require 'lfs'"

about:
  home: http://keplerproject.github.io/luafilesystem/
  license: MIT