package:
  name: lua-llthreads2
  version: 0.1.3

source:
  git_url: git@github.com:moteus/lua-llthreads2.git
  git_tag: v0.1.3

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit

test:
  commands:
    - luajit -e "require 'llthreads2'"

about:
  home: https://github.com/moteus/lua-llthreads2
  license: MIT/X11