package:
  name: sdl2
  version: 2.0.2

source:
  fn: SDL2-2.0.3.tar.gz
  url: http://libsdl.org/release/SDL2-2.0.3.tar.gz
  git_rev: fe6c61d2e9df9ef570e7e80c6e822537

build:
  number: 0
  detect_binary_files_with_prefix: true

about:
  home: http://libsdl.org/
  license: zlib