package:
  name: lua-threads
  version: 0.1.2

source:
  git_url: https://github.com/torch/threads-ffi.git
  git_rev: 6bb6be8

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - sdl2
    - lua-sdl2
    - lua-luaffi [not luajit]
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch
    - sdl2
    - lua-sdl2
    - lua-luaffi [not luajit]
    - cmake

test:
  commands:
    - lua -e "require 'threads'"

about:
  home: https://github.com/torch/threads-ffi
  license: BSD
  summary: Threads for Torch