package:
  name: lua-gnuplot
  version: 1.0

source:
  git_url: git@github.com:torch/gnuplot.git
  git_rev: 35f4250471217f66329781e2818c9ef8cbe7b5f3

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - lua-paths
  run:
    - luajit
    - lua-torch7

test:
  commands:
    - luajit -e "require 'gnuplot'"

about:
  home: https://github.com/torch/gnuplot
  license: BSD