package:
  name: lua-torch
  version: 7.0

source:
  git_url: https://github.com/torch/torch7.git
  git_rev: c05de78096a8f85f7de13000cc4b0b584299940d

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-cwrap
    - lua-paths
    - cmake
    - mkl-rt
  run:
    - lua
    - luarocks
    - lua-cwrap
    - lua-paths
    - mkl-rt

test:
  commands:
    - lua -e "require 'torch'"

about:
  home: https://github.com/torch/torch7
  license: BSD
  summary: Torch7