package:
  name: lua-uuid
  version: 0.2

source:
  git_url: git@github.com:Tieske/uuid.git
  git_tag: version_0.2.0

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit
    - luarocks

test:
  commands:
    - luajit -e "require 'uuid'"

about:
  home: https://github.com/Tieske/uuid
  license: Apache 2.0