package:
  name: lua-sundown
  version: 0.1

source:
  git_url: git@github.com:torch/sundown-ffi.git
  git_rev: 812223802c9c9f359b46478b7bbb1d5b154a88ac

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit

test:
  commands:
    - luajit -e "require 'sundown'"

about:
  home: https://github.com/sampsyo/lua-sundown
  license: MIT