package:
  name: lua-randomkit
  version: 0.1

source:
  git_url: https://github.com/deepmind/torch-randomkit.git
  git_rev: a6d6713

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-cephes
    - lua-penlight # lua 5.1 compatibility
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-cephes
    - lua-penlight # lua 5.1 compatibility

test:
  commands:
    - lua -e "require 'pl'; require 'torch'; require 'randomkit'"

about:
  home: https://github.com/deepmind/torch-randomkit
  license: BSD
  summary: Numpy's randomkit, wrapped for Torch
