package:
  name: lua-nnx
  version: 0.1

source:
  git_url: git@github.com:clementfarabet/lua---nnx.git
  git_rev: c080463

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-nn
    - lua-xlua
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-nn
    - lua-xlua

test:
  commands:
    - lua -e "require 'nnx'"

about:
  home: https://github.com/clementfarabet/lua---nnx
  license: BSD
  summary: A completely unstable and experimental package that extends Torch's builtin nn library