package:
  name: lua-torch-hdf5
  version: 0.0

source:
  git_url: git@github.com:deepmind/torch-hdf5.git
  git_rev: 21e453584952edcc34cf05d629a7cda3b3f81a58

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight
    - lua-torch-totem
    - hdf5
  run:
    - luajit
    - luarocks
    - lua-torch7
    - lua-penlight
    - lua-torch-totem
    - hdf5

test:
  commands:
    - luajit -e "require 'hdf5'"

about:
  home: https://github.com/deepmind/torch-hdf5
  license: BSD