package:
  name: lua-signal
  version: 0.1

source:
  git_url: https://github.com/soumith/torch-signal.git
  git_rev: 94290c5

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-fftw3
    - lua-penlight # lua 5.1 compatibility
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-fftw3
    - lua-penlight # lua 5.1 compatibility
    - cmake

test:
  commands:
    - lua -e "require 'pl'; require 'signal'"

about:
  home: https://github.com/soumith/torch-signal
  license: BSD
  summary: A signal processing toolbox for Torch-7