package:
  name: lua-itorch
  version: 0.1

source:
  git_url: https://github.com/alexbw/iTorch.git
  git_rev: 9c370fc

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - lua-torch
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-lbase64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - jupyter
    - notebook
    - zeromq
  run:
    - lua
    - lua-torch
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-lbase64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - jupyter
    - notebook
    - zeromq

test:
  commands:
    - lua -e "require 'itorch.util'"
    # - lua -e "arg={'$1','$IO_PORTNUM'};require 'itorch.main'"
    # - lua -e "arg={'$1','$IO_STDO','$IO_PORTNUM'};require 'itorch.IOHandler'"
    # - lua -e "require 'itorch.IOHandler'"

about:
  home: https://github.com/facebook/iTorch
  license: BSD
  summary: IPython kernel for Lua / Torch