package:
  name: lua-itorch
  version: 0.1

source:
  git_url: git@github.com:facebook/iTorch.git
  git_rev:  508370b

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - lua-torch
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-lbase64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - jupyter
    - zeromq
  run:
    - lua
    - lua-torch
    - lua-luafilesystem
    - lua-penlight
    - lua-cjson
    - lua-uuid
    - lua-lbase64
    - lua-env
    - lua-image
    - lua-lzmq
    - lua-crypto
    - jupyter
    - zeromq

# test:
  # commands:
    # - lua -e "require 'audio'"

about:
  home: https://github.com/facebook/iTorch
  license: BSD
  summary: IPython kernel for Lua / Torch