package:
  name: lua-paths
  version: 0.1

source:
  git_url: https://github.com/torch/paths.git
  git_rev: 68d579a2d3b1b0bb03a11637632e6e699b14ad80

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - cmake
    - luarocks
  run:
    - luarocks
    - lua

test:
  commands:
    - lua -e "require 'paths'"

about:
  home: https://github.com/torch/paths
  license: BSD
  summary: Paths manipulations