package:
  name: lua-terra
  version: 0.1

source:
  # git_url: https://github.com/zdevito/terra.git
  # git_rev: cac78e6
  git_url: https://github.com/alexbw/terra.git
  git_rev: ab735d5

build:
  detect_binary_files_with_prefix: true
  number: 1

requirements:
  build:
   - lua >=2.0,<5
   - luarocks
   - llvm-clang ==3.5.2
  run:
   - lua >=2.0,<3
   - luarocks
   - llvm-clang ==3.5.2

test:
  commands:
      # Test binary
      - echo "print('All good')" | terra -
      # Test library
      - lua -e "require 'terra'"

about:
  home: https://github.com/zdevito/terra
  license: MIT
  summary: A low-level counterpart to Lua

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
