package:
  name: lua-terra
  version: 0.1

source:
  path: /Users/Alex/Code/terra
  # git_url: https://github.com/zdevito/terra.git
  # git_rev: 2a26c3e

build:
  detect_binary_files_with_prefix: true
  number: 1

requirements:
  build:
   - lua >=2.0,<5
   - luarocks
   - llvm-clang ==3.6.2
  run:
   - lua >=2.0,<3
   - luarocks
   - llvm-clang ==3.6.2

test:
  commands:
    # - lua -e "require 'terra'"

about:
  home: https://github.com/zdevito/terra
  license: MIT
  summary: A low-level counterpart to Lua

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
