package:
  name: lua-terra
  version: 0.1.1

source:
  git_url: https://github.com/zdevito/terra.git
  git_rev: 86cbe2e

build:
  detect_binary_files_with_prefix: true
  number: 0

requirements:
  build:
   - lua
   - luarocks
   - llvm-clang ==3.5.2
   - lua-luaffi [not luajit]
  run:
   - lua
   - luarocks
   - llvm-clang ==3.5.2
   - lua-luaffi [not luajit]

test:
  commands:
      # Test binary
      - echo "print('All good')" | terra -
      # Test library
      - lua -e "require 'terra'"

about:
  home: https://github.com/zdevito/terra
  license: MIT
  summary: A low-level counterpart to Lua

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
