package:
  name: luajit
  version: 2.0.3

source:
  fn: LuaJIT-2.0.3.tar.gz
  url: http://luajit.org/download/LuaJIT-2.0.3.tar.gz
  md5: f14e9104be513913810cd59c8c658dc0

build:
  number: 1
  detect_binary_files_with_prefix: true

test:
  commands:
    - luajit -v

about:
  home: http://luajit.org/
  license: MIT