package:
  name: lua-optim
  version: 1.0.5

source:
  git_url: git@github.com:torch/optim.git
  git_rev: e963a69

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-xlua
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-xlua

test:
  commands:
    - lua -e "require 'optim'"

about:
  home: https://github.com/torch/optim
  license: BSD
  summary: An optimization library for Torch.