package:
  name: lua-autograd
  version: 0.1

source:
  git_url: https://github.com/twitter/torch-autograd.git
  git_rev: fca2070

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-totem
    - lua-nn
    - lua-optim
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-nn
    - lua-optim
    - lua-totem
    - cmake

test:
  commands:
    - lua -e "require 'torch'; require 'autograd'"

about:
  home: https://github.com/twitter/torch-autograd
  license: MIT
  summary: Automatic differentiation for Torch