package:
  name: lua-nngraph
  version: 0.1.1

source:
  git_url: https://github.com/torch/nngraph.git
  git_rev: 1b7d347

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-nn
    - lua-graph
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-nn
    - lua-graph

test:
  commands:
    - lua -e "require 'nngraph'"

about:
  home: https://github.com/torch/nngraph
  license: BSD
  summary: This package provides graphical computation for nn library in Torch7