package:
  name: lua-penlight
  version: 1.3.2

source:
  git_url: git@github.com:stevedonovan/Penlight.git
  git_tag: 1.3.2

build:
  number: 3
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-luafilesystem
  run:
    - luajit
    - luarocks
    - lua-luafilesystem

test:
  commands:
    - luajit -e "require 'pl'"

about:
  home: https://github.com/stevedonovan/Penlight
  license: MIT