package:
  name: lua-penlight
  version: 1.3.2

source:
  git_url: git@github.com:stevedonovan/Penlight.git
  git_tag: 1.3.2

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-luafilesystem
  run:
    - lua
    - luarocks
    - lua-luafilesystem

test:
  commands:
    - LUA_PATH=$(luarocks path --lr-path) LUA_CPATH=$(luarocks path --lr-cpath) && lua -e "require 'pl'"

about:
  home: https://github.com/stevedonovan/Penlight
  license: MIT