package:
  name: lua-totem
  version: 0.1

source:
  git_url: https://github.com/deepmind/torch-totem.git
  git_rev: 4d7a70b

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    - lua-sys
    - lua-nn
    - lua-nngraph
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    - lua-sys
    - lua-nn
    - lua-nngraph

test:
  commands:
    - lua -e "require 'totem'"

about:
  home: https://github.com/deepmind/torch-totem
  license: BSD
  summary: Torch test module