package:
  name: lua-cjson
  version: 2.1.0

source:
  fn: lua-cjson-2.1.0.tar.gz
  url: http://www.kyne.com.au/~mark/software/download/lua-cjson-2.1.0.tar.gz
  md5: 24f270663e9f6ca8ba2a02cef19f7963

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit
    - luarocks

test:
  commands:
    - luajit -e "require 'cjson'"

about:
  home: http://www.kyne.com.au/~mark/software/lua-cjson.php
  license: MIT