package:
  name: lua-torch7
  version: 1.0

source:
  git_url: https://github.com/torch/torch7.git
  git_rev: a0b2db6f0d0a0657ddf1f4608d973138a58830ad

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-cwrap
    - lua-paths
    - cmake
    - mkl-rt
  run:
    - luajit
    - luarocks
    - lua-cwrap
    - lua-paths
    - mkl-rt

test:
  commands:
    - luajit -e "require 'torch'"

about:
  home: http://luajit.org/
  license: MIT