package:
  name: lua-argcheck
  version: 1.0

source:
  git_url: git@github.com:torch/argcheck.git
  git_tag: 1.0.0-0

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luarocks
    - luajit

test:
  commands:
    - luajit -e "require 'argcheck'"

about:
  home: https://github.com/torch/argcheck
  license: BSD