package:
  name: lua-trepl
  version: 0.1.1

source:
  git_url: https://github.com/torch/trepl.git
  git_rev: f2d2f1a

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    # - readline
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    # - readline

test:
  commands:
    - lua -e "require 'trepl'"
    - lua -e "require 'trepl.colors'"
    - lua -e "require 'trepl.colorize'"
    # TODO: I'd like to remove this selector, but luajit+linux is funny with readline
    - lua -e "require 'readline'" [not luajit or not unix]
    - lua -e "require 'treplutils'"

about:
  home: https://github.com/torch/trepl
  license: BSD
  summary: An embedabble, Lua-only REPL for Torch.