package:
  name: lua-threads
  version: 1.0

source:
  git_url: git@github.com:torch/threads-ffi.git
  git_rev: d223e9d60ed04f91016867065a5ef7575d337dce

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
    - sdl2
    - lua-sdl2
  run:
    - luajit
    - luarocks
    - lua-torch7
    - sdl2
    - lua-sdl2

test:
  commands:
    - luajit -e "require 'threads'"

about:
  home: https://github.com/torch/threads-ffi
  license: BSD