package:
  name: lua-graph
  version: 0.1

source:
  git_url: https://github.com/torch/graph.git
  git_rev: d2f14f7

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - graphviz
    - lua-luaffi [not luajit]
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch
    - graphviz
    - lua-luaffi [not luajit]
    - cmake
test:
  commands:
    - lua -e "require 'graph'"

about:
  home: https://github.com/torch/graph
  license: UNKNOWN
  summary: Graph package for Torch