package:
  name: lua-env
  version: 1.0

source:
  git_url: https://github.com/torch/env.git
  git_rev: 832e9365e6a06fbdda863cffc2978c078d073029

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-dok
    - lua-gnuplot
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-dok
    - lua-gnuplot

test:
  commands:
    - lua -e "require 'env'"

about:
  home: https://github.com/torch/env
  license: BSD
  summary: Environment setup for Torch