package:
  name: lua-ipc
  version: 0.1

source:
  git_url: https://github.com/twitter/torch-ipc.git
  git_rev: 3836f0c

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
  run:
    - lua
    - luarocks
    - lua-torch

test:
  commands:
    - lua -e "require 'ipc'"

about:
  home: https://github.com/twitter/torch-autograd
  license: MIT
  summary: Automatic differentiation for Torch