package:
  name: lua-cephes
  version: 0.1

source:
  git_url: https://github.com/deepmind/torch-cephes.git
  git_rev: f8a3a11

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-luaffi [not luajit]
    - lua-penlight # for 5.1 compatibility
    - cmake
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-luaffi [not luajit]
    - lua-penlight # for 5.1 compatibility
    - cmake

test:
  commands:
    - lua -e "require 'pl'; require 'cephes'"

about:
  home: https://github.com/deepmind/torch-cephes
  license: BSD
  summary: Cephes mathematical functions library, wrapped for Torch