package:
  name: flex
  version: 2.5.39

source:
  fn: flex-2.5.39.tar.gz
  url: http://sourceforge.net/projects/flex/files/flex-2.5.39.tar.gz
  md5: e133e9ead8ec0a58d81166b461244fde

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip:
    - [not unix]

requirements:
  build:
    - m4

  run:
    - m4

about:
  home: http://flex.sourceforge.net/
  license: BSD
  license: "Flex is a fast lexical analyser generator."
