package:
  name: lua-luaffi
  version: "0.1"

source:
  git_url: git://github.com/facebook/luaffifb.git
  git_rev: 44672a3
build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luarocks
    - lua

  run:
    - luarocks
    - lua

test:
  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - lua -v
    - lua -e "require 'ffi'"
    - lua -e "require 'ffi.test'"

  # You can also put a file called run_test.lua in the recipe that will be run
  # at test time.

about:
  home: https://github.com/facebook/luaffifb
  license: BSD
  summary: FFI library for calling C functions from lua

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
