package:
  name: gflags
  version: 2.1.2

source:
  url: https://github.com/gflags/gflags/archive/v2.1.2.tar.gz
  fn: v2.1.2.tar.gz

build:
  number: 0
  binary_relocation: true
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake

about:
  home: https://gflags.github.io/gflags/
  license: Apache