package:
  name: lua-hdf5
  version: 0.1

source:
  git_url: git@github.com:deepmind/torch-hdf5.git
  git_rev: d7e8a6d

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    - lua-totem
    - hdf5
    - lua-luaffi [not luajit]
    - lua-luabitop [not luajit]
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-penlight
    - lua-totem
    - hdf5
    - lua-luaffi [not luajit]
    - lua-luabitop [not luajit]

test:
  commands:
    - lua -e "require 'hdf5'"

about:
  home: https://github.com/deepmind/torch-hdf5
  license: BSD
  summary: Interface to HDF5 library