package:
  name: lua-nn
  version: 0.1

source:
  git_url: https://github.com/torch/nn.git
  git_rev:  e82d8cb

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
    - lua-luaffi [not luajit]
  run:
    - lua
    - luarocks
    - lua-torch
    - lua-luaffi [not luajit]

test:
  commands:
    - lua -e "require 'nn'"

about:
  home: https://github.com/torch/nn
  license: BSD
  summary: Neural Network package for Torch