package:
  name: lua-nn
  version: 1.0

source:
  git_url: git@github.com:torch/nn.git
  git_rev: f788c4f9110cd22dadbe143c205d83e1f92478e0

build:
  number: 2
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-torch
  run:
    - lua
    - luarocks
    - lua-torch

test:
  commands:
    - lua -e "require 'nn'"

about:
  home: https://github.com/torch/nn
  license: BSD