package:
  name: lua-crypto
  version: 2.1.0

source:
  git_url: git@github.com:mkottman/luacrypto.git
  git_rev: 8c3f7f0caf023fe327f9e60391fc80df2d08a169

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
  run:
    - luajit
    - luarocks

test:
  commands:
    - luajit -e "require 'crypto'"

about:
  home: http://mkottman.github.com/luacrypto/
  license: MIT