package:
  name: lua-argcheck
  version: 1.0.1

source:
  git_url: https://github.com/torch/argcheck.git
  git_rev: 91344af

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - lua
    - luarocks
    - lua-luaffi [not luajit]
    - lua-sundown
  run:
    - lua
    - luarocks
    - lua-luaffi [not luajit]
    - lua-sundown

test:
  commands:
    - lua -e "require 'argcheck'"
    - lua -e "require 'argcheck.init'"
    - lua -e "require 'argcheck.env'"
    - lua -e "require 'argcheck.utils'"
    - lua -e "require 'argcheck.doc'"
    - lua -e "require 'argcheck.dump'"

about:
  home: https://github.com/torch/argcheck
  license: BSD
  summary: Advanced function argument checker
