package:
  name: lua-pprint
  version: 0.0

source:
  git_url: git@github.com:deepmind/lua-pprint.git
  git_rev: 6a5560ece761b0e32c1a2cfd09e2024936b16a09

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - luajit
    - luarocks
    - lua-torch7
  run:
    - luajit
    - luarocks
    - lua-torch7

test:
  commands:
    - luajit -e "require 'pprint'"

about:
  home: https://github.com/deepmind/lua-pprint
  license: BSD